
package com.itheima.crm.service05.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceImpl", targetNamespace = "http://impl.service.crm.itheima.com/")
@XmlSeeAlso({
})
public interface CustomerServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindByTelephoneResponse")
    public boolean findByTelephone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service05.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.crm.service05.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "activeCode", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.ActiveCode")
    @ResponseWrapper(localName = "activeCodeResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.ActiveCodeResponse")
    public boolean activeCode(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regist", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.RegistResponse")
    public String regist(
            @WebParam(name = "arg0", targetNamespace = "")
                    Customer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service05.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itheima.crm.service05.impl.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.LoginResponse")
    public Customer login(
            @WebParam(name = "arg0", targetNamespace = "")
                    Customer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomers2FixedArea", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.AssignCustomers2FixedArea")
    @ResponseWrapper(localName = "assignCustomers2FixedAreaResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.AssignCustomers2FixedAreaResponse")
    public void assignCustomers2FixedArea(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.crm.service05.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCusByFixedId", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindCusByFixedId")
    @ResponseWrapper(localName = "findCusByFixedIdResponse", targetNamespace = "http://impl.service.crm.itheima.com/", className = "com.itheima.crm.service05.impl.FindCusByFixedIdResponse")
    public List<Customer> findCusByFixedId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
